### ISSUE TITLE
Improve tracing of curve in SVG files

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/electrochemistry-data#10]
Some curves were not traced properly in Inkscape. Corners and edges should be removed. Some of the following files might be ok. Cross-checking does not hurt...

- [x] alves_2011_electrochemistry_6010 (see echemdb/website#136)
- [ ] briega-martos_2021_cation_48 (see echemdb/website#136)
  - [ ] Check again
- [x] endo_1999_in-situ_19 (see echemdb/website#136)
- [x] engstfeld_2018_polycrystalline_17743 (see echemdb/website#136)
- [x] gomez-marin_2012_surface_558 (see echemdb/website#136)
- [x] hamad_2003_electrosorption_211 (see echemdb/website#136)
- [x] horswell_2004_a_10970 - 3 - (see echemdb/website#136)
- [x] jovic_1999_cyclic_247 - 7 - (see echemdb/website#136)
- [x] kerner_2002_measurement_2055 - 9 - (see echemdb/website#136)
- [ ] li_2000_chronocoulometric_95 - 4
- [ ] lipkowski_1998_ionic_2875 - 4
- [ ] mello_2018_bromide_18562 - 18
- [ ] mello_2018_understanding_J3045 - 32
- [ ] nakamura_2011_structure_165433 - 5
- [ ] nakamura_2014_structural_22136 - 1
- [ ] ocko_1997_halide_55 - 1
- [ ] pajkossy_1996_impedance_209 - 10
- [ ] pajkossy_2001_double_3063 - 3
- [ ] rehim_1998_electrochemical_1103 - 1
- [ ] shi_1996_chloride_225 - 4
- [ ] wandlowski_1996_structural_10277 - 2
- [ ] wang_1997_lateral_1 - 3
- [ ] wang_1996_ordered_6672 - 1
- [ ] zei_1991_the_295 - 2
